spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.38:33062/agencia?serverTimezone=UTC
    username: root
    password: Admin7
  jpa:
    hibernate:
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
springdoc:
  packages-to-scan:
    - com.ejercicio.controller
  paths-to-match:
    - /**
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.38:8761/eureka
  instance:
    instance-id: ${spring.application.name}-${spring.application.instance_id:${random.int[0,99]}}
    prefer-ip-address: true
server:
  port: 0
