spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.34:33062/escuela?serverTimezone=UTC
    username: root
    password: Admin7   
  jpa:
    hibernate:
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}-${spring.application.instance_id:${random.int[0,99]}}
    hostname: 192.168.1.34
    non-secure-port: 8081
server:
  port: 0 #${random.int[1024,65536]}
